version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build phase. No actual build commands needed.

artifacts:
  files:
    - '**/*'
